/** Autogenerated Main.cpp. */

// ===============================| Include only the DSP files  |===============================

#include <hi_dsp_library/hi_dsp_library.h>
#include <hi_faust/hi_faust.h>
#include "includes.h"
// =========================| Now we can add the rest of the codebase |=========================

#include <JuceHeader.h>

// =====================================| Project Factory |=====================================

namespace project
{

struct Factory: public scriptnode::dll::StaticLibraryHostFactory
{
	Factory()
	{
		TempoSyncer::initTempoData();
		// Node registrations -----------------------------------------------------------------
		
		registerPolyNode<project::minmaxtest<1>, project::minmaxtest<NUM_POLYPHONIC_VOICES>>();
		registerDataNode<project::Harmonicoscillator_networkdata>();
		registerDataNode<project::HarmonicOscillatorwithsliderpackmorphing_networkdata>();
		registerDataNode<project::SampleFM_networkdata>();
		registerDataNode<project::Switch_networkdata>();
		registerDataNode<project::WeirdDelay_networkdata>();
		registerDataNode<project::_4WaySwitch_networkdata>();
	}
};
}

scriptnode::dll::FactoryBase* hise::FrontendHostFactory::createStaticFactory()
{
	return new project::Factory();
}

