/* Autogenerated include file. */
#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( push )
#pragma warning( disable : 4189 4373)
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#endif

// Include compiled network files -------------------------------

#include "HarmonicOscillatorwithsliderpackmorphing_networkdata.h"
#include "Harmonicoscillator_networkdata.h"
#include "minmaxtest.h"
#include "SampleFM_networkdata.h"
#include "Switch_networkdata.h"
#include "WeirdDelay_networkdata.h"
#include "_4WaySwitch_networkdata.h"

#if (defined (_WIN32) || defined (_WIN64))
#pragma warning( pop )
#else
#pragma clang diagnostic pop
#endif

